// <auto-generated />
using System;
using APIPSI16.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPSI16.Migrations
{
    [DbContext(typeof(xcleratesystemslinks_SampleDBContext))]
    [Migration("20260222143117_AddSessionsTable")]
    partial class AddSessionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIPSI16.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId")
                        .HasName("PK__AuditLog__EB5F6CBDB08DE115");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("APIPSI16.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChatId")
                        .HasName("PK__Chat__A9FBE7C651A747BD");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("APIPSI16.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId")
                        .HasName("PK__ChatMess__C87C0C9C7250148E");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("APIPSI16.Models.ChatUser", b =>
                {
                    b.Property<int>("ChatUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatUserId"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("member");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatUserId")
                        .HasName("PK__ChatUser__BFA9F7900B8CB40A");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ChatId", "UserId" }, "UQ_Chat_User")
                        .IsUnique();

                    b.ToTable("ChatUsers");
                });

            modelBuilder.Entity("APIPSI16.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CompanyId")
                        .HasName("PK__Companie__2D971CAC7600FB81");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("APIPSI16.Models.CompanyMember", b =>
                {
                    b.Property<int>("CompanyMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyMemberId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CompanyMemberId")
                        .HasName("PK__CompanyM__F1920989987E4A54");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CompanyId", "UserId" }, "UQ_Company_User")
                        .IsUnique();

                    b.ToTable("CompanyMembers");
                });

            modelBuilder.Entity("APIPSI16.Models.Connection", b =>
                {
                    b.Property<int>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectionId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("AddresseeUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("ConnectionId")
                        .HasName("PK__Connecti__404A64931F69BCCF");

                    b.HasIndex(new[] { "RequesterUserId", "AddresseeUserId" }, "UQ__Connecti__D964BF246B6D1B80")
                        .IsUnique();

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("APIPSI16.Models.EmployerCandidateHistory", b =>
                {
                    b.Property<int>("EmployerCandidateHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerCandidateHistoryId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("LastContactAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StageReached")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployerCandidateHistoryId")
                        .HasName("PK__Employer__7ED6A363F8F4F90F");

                    b.HasIndex("OpportunityId");

                    b.HasIndex(new[] { "CompanyId", "LastContactAt" }, "IX_ECH_Company_LastContact")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "CompanyId", "UserId" }, "IX_ECH_Company_User");

                    b.HasIndex(new[] { "UserId" }, "IX_ECH_User");

                    b.HasIndex(new[] { "CompanyId", "UserId", "OpportunityId" }, "UQ_EmployerCandidateHistory")
                        .IsUnique()
                        .HasFilter("[OpportunityId] IS NOT NULL");

                    b.ToTable("EmployerCandidateHistory", (string)null);
                });

            modelBuilder.Entity("APIPSI16.Models.InterviewRound", b =>
                {
                    b.Property<int>("InterviewRoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewRoundId"));

                    b.Property<int?>("InterviewerUserId")
                        .HasColumnType("int");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Outcome")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RoundNumber")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime");

                    b.HasKey("InterviewRoundId")
                        .HasName("PK__Intervie__33D9F1FB804C69B8");

                    b.HasIndex("InterviewerUserId");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("InterviewRounds");
                });

            modelBuilder.Entity("APIPSI16.Models.JobApplication", b =>
                {
                    b.Property<int>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicationId"));

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<byte?>("Stage")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JobApplicationId")
                        .HasName("PK__JobAppli__BD557F85702879F0");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("UserId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("APIPSI16.Models.JobRole", b =>
                {
                    b.Property<int>("JobRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobRoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobRoleId")
                        .HasName("PK__JobRoles__6D8BAC2F3B334D72");

                    b.HasIndex(new[] { "Name" }, "UQ__JobRoles__737584F68DB4257F")
                        .IsUnique();

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("APIPSI16.Models.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalityId"));

                    b.Property<string>("Isocode")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("ISOCode")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NationalityId")
                        .HasName("PK__National__F628E744043E379B");

                    b.HasIndex(new[] { "Name" }, "UQ__National__737584F6FEC464F0")
                        .IsUnique();

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("APIPSI16.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E122B839BE3");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("APIPSI16.Models.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<string>("CompensationCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CompensationMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CompensationMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("CreatorID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("EmploymentType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("RemoteOption")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("SeniorityLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Oportuni__3214EC274DEA57B2");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("APIPSI16.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<byte>("Visibility")
                        .HasColumnType("tinyint");

                    b.HasKey("PostId")
                        .HasName("PK__Posts__AA1260184B9F8F56");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("APIPSI16.Models.PostComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModerated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModeratedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__PostComm__C3B4DFCA72C8D2D9");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("APIPSI16.Models.PostReaction", b =>
                {
                    b.Property<int>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<byte>("ReactionType")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReactionId")
                        .HasName("PK__PostReac__46DDF9B4004EE135");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId", "UserId", "ReactionType" }, "UX_Post_User_Reaction")
                        .IsUnique();

                    b.ToTable("PostReactions");
                });

            modelBuilder.Entity("APIPSI16.Models.ProfileEducation", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<string>("Degree")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EducationId")
                        .HasName("PK__ProfileE__4BBE380527A7D966");

                    b.HasIndex("UserId");

                    b.ToTable("ProfileEducations");
                });

            modelBuilder.Entity("APIPSI16.Models.ProfileExperience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ExperienceId")
                        .HasName("PK__ProfileE__2F4E34491AA78603");

                    b.HasIndex("UserId");

                    b.ToTable("ProfileExperiences");
                });

            modelBuilder.Entity("APIPSI16.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("RatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("RatedByUserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("APIPSI16.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId")
                        .HasName("PK__Session__SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("APIPSI16.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SkillId")
                        .HasName("PK__Skills__DFA0918781313143");

                    b.HasIndex(new[] { "Name" }, "UQ__Skills__737584F61738EFED")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("APIPSI16.Models.SkillEndorsement", b =>
                {
                    b.Property<int>("EndorsementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EndorsementId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EndorserUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserSkillId")
                        .HasColumnType("int");

                    b.HasKey("EndorsementId")
                        .HasName("PK__SkillEnd__DBB8336F15D1AEF4");

                    b.HasIndex("EndorserUserId");

                    b.HasIndex(new[] { "UserSkillId", "EndorserUserId" }, "UX_Endorse")
                        .IsUnique();

                    b.ToTable("SkillEndorsements");
                });

            modelBuilder.Entity("APIPSI16.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateOnly?>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("JobPreference")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Nationality")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfileBio")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Profile_Bio");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACFE71B925");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("APIPSI16.Models.UserJobPreference", b =>
                {
                    b.Property<int>("UserJobPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserJobPreferenceId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserJobPreferenceId")
                        .HasName("PK__UserJobP__F82C54A77C80E128");

                    b.HasIndex("JobRoleId");

                    b.HasIndex(new[] { "UserId", "JobRoleId" }, "UQ_User_JobRole")
                        .IsUnique();

                    b.ToTable("UserJobPreferences");
                });

            modelBuilder.Entity("APIPSI16.Models.UserSkill", b =>
                {
                    b.Property<int>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSkillId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EndorsementCount")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserSkillId")
                        .HasName("PK__UserSkil__2F28BE56D1484E42");

                    b.HasIndex("SkillId");

                    b.HasIndex(new[] { "UserId", "SkillId" }, "UX_User_Skill")
                        .IsUnique();

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("APIPSI16.Models.AuditLog", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.Chat", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "CreatedByUser")
                        .WithMany("Chats")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Chat__CreatedByU__32E0915F");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("APIPSI16.Models.ChatMessage", b =>
                {
                    b.HasOne("APIPSI16.Models.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatMessa__ChatI__3F466844");

                    b.HasOne("APIPSI16.Models.User", "SenderUser")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderUserId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatMessa__Sende__403A8C7D");

                    b.Navigation("Chat");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("APIPSI16.Models.ChatUser", b =>
                {
                    b.HasOne("APIPSI16.Models.Chat", "Chat")
                        .WithMany("ChatUsers")
                        .HasForeignKey("ChatId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatUsers__ChatI__38996AB5");

                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("ChatUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatUsers__UserI__398D8EEE");

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.CompanyMember", b =>
                {
                    b.HasOne("APIPSI16.Models.Company", "Company")
                        .WithMany("CompanyMembers")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMembers_Company");

                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("CompanyMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMembers_User");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.EmployerCandidateHistory", b =>
                {
                    b.HasOne("APIPSI16.Models.Company", "Company")
                        .WithMany("EmployerCandidateHistories")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployerC__Compa__72C60C4A");

                    b.HasOne("APIPSI16.Models.Opportunity", "Opportunity")
                        .WithMany("EmployerCandidateHistories")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("FK__EmployerC__Oppor__74AE54BC");

                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("EmployerCandidateHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployerC__UserI__73BA3083");

                    b.Navigation("Company");

                    b.Navigation("Opportunity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.InterviewRound", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "InterviewerUser")
                        .WithMany("InterviewRounds")
                        .HasForeignKey("InterviewerUserId")
                        .HasConstraintName("FK__Interview__Inter__43D61337");

                    b.HasOne("APIPSI16.Models.JobApplication", "JobApplication")
                        .WithMany("InterviewRounds")
                        .HasForeignKey("JobApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK__Interview__JobAp__42E1EEFE");

                    b.Navigation("InterviewerUser");

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("APIPSI16.Models.JobApplication", b =>
                {
                    b.HasOne("APIPSI16.Models.Opportunity", "Opportunity")
                        .WithMany("JobApplications")
                        .HasForeignKey("OpportunityId")
                        .IsRequired()
                        .HasConstraintName("FK__JobApplic__Oppor__3F115E1A");

                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("JobApplications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__JobApplic__UserI__40058253");

                    b.Navigation("Opportunity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.Notification", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "ActorUser")
                        .WithMany("NotificationActorUsers")
                        .HasForeignKey("ActorUserId")
                        .HasConstraintName("FK__Notificat__Actor__3A4CA8FD");

                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__395884C4");

                    b.Navigation("ActorUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.Opportunity", b =>
                {
                    b.HasOne("APIPSI16.Models.Company", "Company")
                        .WithMany("Opportunities")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Opportunities_Company");

                    b.HasOne("APIPSI16.Models.User", "Creator")
                        .WithMany("Opportunities")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Opportunities_CreatedBy");

                    b.Navigation("Company");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("APIPSI16.Models.Post", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Posts__UserId__29221CFB");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.PostComment", b =>
                {
                    b.HasOne("APIPSI16.Models.PostComment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("FK__PostComme__Paren__2EDAF651");

                    b.HasOne("APIPSI16.Models.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__PostComme__PostI__2CF2ADDF");

                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PostComme__UserI__2DE6D218");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.PostReaction", b =>
                {
                    b.HasOne("APIPSI16.Models.Post", "Post")
                        .WithMany("PostReactions")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__PostReact__PostI__339FAB6E");

                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("PostReactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PostReact__UserI__3493CFA7");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.ProfileEducation", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("ProfileEducations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ProfileEd__UserI__151B244E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.ProfileExperience", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("ProfileExperiences")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ProfileEx__UserI__123EB7A3");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.Rating", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "RatedByUser")
                        .WithMany()
                        .HasForeignKey("RatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RatedByUser");
                });

            modelBuilder.Entity("APIPSI16.Models.Session", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Session__UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.SkillEndorsement", b =>
                {
                    b.HasOne("APIPSI16.Models.User", "EndorserUser")
                        .WithMany("SkillEndorsements")
                        .HasForeignKey("EndorserUserId")
                        .IsRequired()
                        .HasConstraintName("FK__SkillEndo__Endor__245D67DE");

                    b.HasOne("APIPSI16.Models.UserSkill", "UserSkill")
                        .WithMany("SkillEndorsements")
                        .HasForeignKey("UserSkillId")
                        .IsRequired()
                        .HasConstraintName("FK__SkillEndo__UserS__236943A5");

                    b.Navigation("EndorserUser");

                    b.Navigation("UserSkill");
                });

            modelBuilder.Entity("APIPSI16.Models.UserJobPreference", b =>
                {
                    b.HasOne("APIPSI16.Models.JobRole", "JobRole")
                        .WithMany("UserJobPreferences")
                        .HasForeignKey("JobRoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UserJobPr__JobRo__02084FDA");

                    b.Navigation("JobRole");
                });

            modelBuilder.Entity("APIPSI16.Models.UserSkill", b =>
                {
                    b.HasOne("APIPSI16.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSkill__Skill__1EA48E88");

                    b.HasOne("APIPSI16.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSkill__UserI__1DB06A4F");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIPSI16.Models.Chat", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatUsers");
                });

            modelBuilder.Entity("APIPSI16.Models.Company", b =>
                {
                    b.Navigation("CompanyMembers");

                    b.Navigation("EmployerCandidateHistories");

                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("APIPSI16.Models.JobApplication", b =>
                {
                    b.Navigation("InterviewRounds");
                });

            modelBuilder.Entity("APIPSI16.Models.JobRole", b =>
                {
                    b.Navigation("UserJobPreferences");
                });

            modelBuilder.Entity("APIPSI16.Models.Opportunity", b =>
                {
                    b.Navigation("EmployerCandidateHistories");

                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("APIPSI16.Models.Post", b =>
                {
                    b.Navigation("PostComments");

                    b.Navigation("PostReactions");
                });

            modelBuilder.Entity("APIPSI16.Models.PostComment", b =>
                {
                    b.Navigation("InverseParentComment");
                });

            modelBuilder.Entity("APIPSI16.Models.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("APIPSI16.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ChatMessages");

                    b.Navigation("ChatUsers");

                    b.Navigation("Chats");

                    b.Navigation("CompanyMembers");

                    b.Navigation("EmployerCandidateHistories");

                    b.Navigation("InterviewRounds");

                    b.Navigation("JobApplications");

                    b.Navigation("NotificationActorUsers");

                    b.Navigation("NotificationUsers");

                    b.Navigation("Opportunities");

                    b.Navigation("PostComments");

                    b.Navigation("PostReactions");

                    b.Navigation("Posts");

                    b.Navigation("ProfileEducations");

                    b.Navigation("ProfileExperiences");

                    b.Navigation("Sessions");

                    b.Navigation("SkillEndorsements");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("APIPSI16.Models.UserSkill", b =>
                {
                    b.Navigation("SkillEndorsements");
                });
#pragma warning restore 612, 618
        }
    }
}
