// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using APIPSI16.Models;
using Microsoft.EntityFrameworkCore;

namespace APIPSI16.Data;

public partial class xcleratesystemslinks_SampleDBContext : DbContext
{
    public xcleratesystemslinks_SampleDBContext()
    {
    }

    public xcleratesystemslinks_SampleDBContext(DbContextOptions<xcleratesystemslinks_SampleDBContext> options)
    : base(options)
    {
    }


    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Chat> Chats { get; set; }

    public virtual DbSet<ChatMessage> ChatMessages { get; set; }

    public virtual DbSet<ChatUser> ChatUsers { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<CompanyMember> CompanyMembers { get; set; }

    public virtual DbSet<Connection> Connections { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<EmployerCandidateHistory> EmployerCandidateHistories { get; set; }

    public virtual DbSet<InterviewRound> InterviewRounds { get; set; }

    public virtual DbSet<JobApplication> JobApplications { get; set; }

    public virtual DbSet<JobRole> JobRoles { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Nationality> Nationalities { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Opportunity> Opportunities { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostComment> PostComments { get; set; }

    public virtual DbSet<PostReaction> PostReactions { get; set; }

    public virtual DbSet<ProfileEducation> ProfileEducations { get; set; }

    public virtual DbSet<ProfileExperience> ProfileExperiences { get; set; }

    public virtual DbSet<Session> Sessions { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    public virtual DbSet<SkillEndorsement> SkillEndorsements { get; set; }

    public virtual DbSet<SkillValidationRequest> SkillValidationRequests { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserJobPreference> UserJobPreferences { get; set; }

    public virtual DbSet<UserSkill> UserSkills { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=sql.bsite.net\\MSSQL2016;Database=xcleratesystemslinks_SampleDB;User Id=xcleratesystemslinks_SampleDB;Password=XcelerateDB;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.AuditLogId).HasName("PK__AuditLog__EB5F6CBDB08DE115");

            entity.ToTable("AuditLog");

            entity.Property(e => e.Action).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TargetType).HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AuditLog_User");
        });

        modelBuilder.Entity<Chat>(entity =>
        {
            entity.HasKey(e => e.ChatId).HasName("PK__Chat__A9FBE7C651A747BD");

            entity.ToTable("Chat");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Type).HasMaxLength(50);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Chats)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Chat__CreatedByU__32E0915F");
        });

        modelBuilder.Entity<ChatMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__ChatMess__C87C0C9C7250148E");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Chat).WithMany(p => p.ChatMessages)
                .HasForeignKey(d => d.ChatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ChatMessa__ChatI__3F466844");

            entity.HasOne(d => d.SenderUser).WithMany(p => p.ChatMessages)
                .HasForeignKey(d => d.SenderUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ChatMessa__Sende__403A8C7D");
        });

        modelBuilder.Entity<ChatUser>(entity =>
        {
            entity.HasKey(e => e.ChatUserId).HasName("PK__ChatUser__BFA9F7900B8CB40A");

            entity.HasIndex(e => new { e.ChatId, e.UserId }, "UQ_Chat_User").IsUnique();

            entity.Property(e => e.JoinedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasDefaultValue("member");

            entity.HasOne(d => d.Chat).WithMany(p => p.ChatUsers)
                .HasForeignKey(d => d.ChatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ChatUsers__ChatI__38996AB5");

            entity.HasOne(d => d.User).WithMany(p => p.ChatUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ChatUsers__UserI__398D8EEE");
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasKey(e => e.CompanyId).HasName("PK__Companie__2D971CAC7600FB81");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Industry).HasMaxLength(100);
            entity.Property(e => e.Location).HasMaxLength(150);
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.CompanyLogoUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Connection>(entity =>
        {
            entity.HasKey(e => e.ConnectionId).HasName("PK__Connecti__404A64931F69BCCF");

            entity.HasIndex(e => new { e.RequesterUserId, e.AddresseeUserId }, "UQ__Connecti__D964BF246B6D1B80").IsUnique();

            entity.Property(e => e.AcceptedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<EmployerCandidateHistory>(entity =>
        {
            entity.HasKey(e => e.EmployerCandidateHistoryId).HasName("PK__Employer__7ED6A363F8F4F90F");
            entity.ToTable("EmployerCandidateHistory");
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.CountryId).HasName("PK__Countries__CountryId");
            entity.ToTable("Countries");

            entity.HasIndex(e => e.Name, "UQ__Countries__Name").IsUnique();
            entity.HasIndex(e => e.Code, "UQ__Countries__Code").IsUnique();

            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Code).HasMaxLength(2);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__Locations__LocationId");
            entity.ToTable("Locations");

            entity.HasIndex(e => e.CountryId, "IX_Locations_CountryId");

            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Region).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Country)
                .WithMany(p => p.Locations)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Locations_Countries");
        });


        modelBuilder.Entity<JobApplication>(entity =>
        {
            entity.HasKey(e => e.JobApplicationId).HasName("PK__JobApplications__JobApplicationId");
            entity.ToTable("JobApplications");

            entity.Property(e => e.Status).HasDefaultValue((byte)0);
            entity.Property(e => e.AppliedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(50).IsUnicode(false);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20).IsUnicode(false);
            entity.Property(e => e.ProfessionalUrl).HasMaxLength(300);
            entity.Property(e => e.PortfolioUrl).HasMaxLength(300);
            entity.Property(e => e.SelectedJobRoleIds).HasMaxLength(500);
            entity.Property(e => e.ApplicantResponse).IsRequired(false);

            entity.HasOne(d => d.Opportunity)
                .WithMany(p => p.JobApplications)
                .HasForeignKey(d => d.OpportunityId)
                .HasConstraintName("FK_JobApplications_Opportunity");

            entity.HasOne(d => d.User)
                .WithMany(p => p.JobApplications)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_JobApplications_User");
        });

        modelBuilder.Entity<JobRole>(entity =>
        {
            entity.HasKey(e => e.JobRoleId).HasName("PK__JobRoles__6D8BAC2F3B334D72");

            entity.HasIndex(e => e.Name, "UQ__JobRoles__737584F68DB4257F").IsUnique();

            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<Nationality>(entity =>
        {
            entity.HasKey(e => e.NationalityId).HasName("PK__National__F628E744043E379B");

            entity.HasIndex(e => e.Name, "UQ__National__737584F6FEC464F0").IsUnique();

            entity.Property(e => e.Isocode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("ISOCode");
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E122B839BE3");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Type).HasMaxLength(100);

            entity.HasOne(d => d.ActorUser).WithMany(p => p.NotificationActorUsers)
                .HasForeignKey(d => d.ActorUserId)
                .HasConstraintName("FK__Notificat__Actor__3A4CA8FD");

            entity.HasOne(d => d.User).WithMany(p => p.NotificationUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notificat__UserI__395884C4");
        });

        modelBuilder.Entity<Opportunity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Opportunities__ID");
            entity.ToTable("Opportunities");

            entity.Property(e => e.Id)
                .HasColumnName("ID")
                .ValueGeneratedOnAdd();

            entity.Property(e => e.Title).HasMaxLength(100);
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.CreatorId).HasColumnName("CreatorID");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.RequiredJobRoleIds)
                .HasMaxLength(500)
                .HasColumnName("RequiredJobRoleIds")
                .HasDefaultValue(null);

            entity.HasOne(d => d.Company)
                .WithMany(p => p.Opportunities)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("FK_Opportunities_Company");

            entity.HasOne(d => d.Creator)
                .WithMany()
                .HasForeignKey(d => d.CreatorId)
                .HasConstraintName("FK_Opportunities_CreatedBy");

            entity.HasOne(d => d.LocationNav)
                .WithMany()
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK_Opportunities_Location");

            entity.HasOne(d => d.CountryNav)
                .WithMany()
                .HasForeignKey(d => d.CountryId)
                .HasConstraintName("FK_Opportunities_Country");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__Posts__AA1260184B9F8F56");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.Posts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Posts__UserId__29221CFB");
        });

        modelBuilder.Entity<PostComment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__PostComm__C3B4DFCA72C8D2D9");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment)
                .HasForeignKey(d => d.ParentCommentId)
                .HasConstraintName("FK__PostComme__Paren__2EDAF651");

            entity.HasOne(d => d.Post).WithMany(p => p.PostComments)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostComme__PostI__2CF2ADDF");

            entity.HasOne(d => d.User).WithMany(p => p.PostComments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostComme__UserI__2DE6D218");
        });

        modelBuilder.Entity<PostReaction>(entity =>
        {
            entity.HasKey(e => e.ReactionId).HasName("PK__PostReac__46DDF9B4004EE135");

            entity.HasIndex(e => new { e.PostId, e.UserId, e.ReactionType }, "UX_Post_User_Reaction").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Post).WithMany(p => p.PostReactions)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostReact__PostI__339FAB6E");

            entity.HasOne(d => d.User).WithMany(p => p.PostReactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostReact__UserI__3493CFA7");
        });

        modelBuilder.Entity<ProfileEducation>(entity =>
        {
            entity.HasKey(e => e.EducationId).HasName("PK__ProfileE__4BBE380527A7D966");

            entity.Property(e => e.Degree).HasMaxLength(200);
            entity.Property(e => e.FieldOfStudy).HasMaxLength(200);
            entity.Property(e => e.School).HasMaxLength(200);

            entity.HasOne(d => d.User).WithMany(p => p.ProfileEducations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProfileEd__UserI__151B244E");
        });

        modelBuilder.Entity<ProfileExperience>(entity =>
        {
            entity.HasKey(e => e.ExperienceId).HasName("PK__ProfileE__2F4E34491AA78603");

            entity.Property(e => e.CompanyName).HasMaxLength(200);
            entity.Property(e => e.Location).HasMaxLength(150);
            entity.Property(e => e.Title).HasMaxLength(150);

            entity.HasOne(d => d.User).WithMany(p => p.ProfileExperiences)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProfileEx__UserI__123EB7A3");
        });

        modelBuilder.Entity<Session>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__Session__SessionId");

            entity.ToTable("Session");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.Property(e => e.ExpiresAt)
                .HasColumnType("datetime");

            entity.Property(e => e.InvalidatedAt)
                .HasColumnType("datetime");

            entity.Property(e => e.Token)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.User)
                .WithMany(p => p.Sessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Session__UserId");
        });

        modelBuilder.Entity<Skill>(entity =>
        {
            entity.HasKey(e => e.SkillId).HasName("PK__Skills__DFA0918781313143");

            entity.HasIndex(e => e.Name, "UQ__Skills__737584F61738EFED").IsUnique();

            entity.Property(e => e.Name).HasMaxLength(150);
        });

        modelBuilder.Entity<SkillEndorsement>(entity =>
        {
            entity.HasKey(e => e.EndorsementId).HasName("PK__SkillEnd__DBB8336F15D1AEF4");

            entity.HasIndex(e => new { e.UserSkillId, e.EndorserUserId }, "UX_Endorse").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.EndorserUser).WithMany(p => p.SkillEndorsements)
                .HasForeignKey(d => d.EndorserUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SkillEndo__Endor__245D67DE");

            entity.HasOne(d => d.UserSkill).WithMany(p => p.SkillEndorsements)
                .HasForeignKey(d => d.UserSkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SkillEndo__UserS__236943A5");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACFE71B925");

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PasswordHash).HasMaxLength(200);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ProfileBio)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("Profile_Bio");
            entity.Property(e => e.ProfilePictureUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.SubscriptionPlan).HasDefaultValue(0);
            entity.Property(e => e.EmployerRequestDocumentUrl).HasMaxLength(500);
            entity.Property(e => e.EmployerRequestNote).HasMaxLength(1000);

            entity.HasOne(d => d.LocationNav)
                .WithMany()
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK_Users_Location");

            entity.HasOne(d => d.CountryNav)
                .WithMany()
                .HasForeignKey(d => d.CountryId)
                .HasConstraintName("FK_Users_Country");
        });

        modelBuilder.Entity<UserJobPreference>(entity =>
        {
            entity.HasKey(e => e.UserJobPreferenceId).HasName("PK__UserJobP__F82C54A77C80E128");

            entity.HasIndex(e => new { e.UserId, e.JobRoleId }, "UQ_User_JobRole").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.JobRole).WithMany(p => p.UserJobPreferences)
                .HasForeignKey(d => d.JobRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserJobPr__JobRo__02084FDA");
        });

        modelBuilder.Entity<UserSkill>(entity =>
        {
            entity.HasKey(e => e.UserSkillId).HasName("PK__UserSkil__2F28BE56D1484E42");

            entity.HasIndex(e => new { e.UserId, e.SkillId }, "UX_User_Skill").IsUnique();

            entity.Property(e => e.AddedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Skill).WithMany(p => p.UserSkills)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserSkill__Skill__1EA48E88");

            entity.HasOne(d => d.User).WithMany(p => p.UserSkills)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserSkill__UserI__1DB06A4F");
        });

        modelBuilder.Entity<SkillValidationRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId);

            entity.ToTable("SkillValidationRequests");

            entity.Property(e => e.RequestedSkillName).HasMaxLength(200);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.DocumentUrl).HasMaxLength(500);
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("getutcdate()");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne(d => d.Skill).WithMany()
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}